### PR TITLE
OrElse callback should be able to change Ok type

### LINKED ISSUE #411: orElse should accept new Ok types
Current signature:
```ts
class Result<T, E> {
  orElse<A>(
    callback: (error: E) => Result<T, A>
  ): Result<T, A> { ... }
}
```

Suggested signature:
```ts
class Result<T, E> {
  orElse<T2, E2>(
    callback: (error: E) => Result<T2, E2>
  ): Result<T | T2, E2> { ... }
}
```

Example scenario:
```ts
const getAnimal = (name: string): ResultAsync<Dog | Cat, Error> =>
  getDog(name)
    .orElse((err) => err instanceof NotFoundError ? getCat(name) : errAsync(err))
```

Current workaround:

```ts
const getAnimal = (name: string): ResultAsync<Dog | Cat, Error> =>
  (getDog(name) as ResultAsync<Dog | Cat, Error>)
    .orElse((err) => err instanceof NotFoundError ? getCat(name) : errAsync(err))
```

### LINKED ISSUE #437: orElse returns the wrong type when the callback changes the ok type
`Result` is broken. It doesn't track ok type changes.
```typescript
import { Result, ok, err } from 'neverthrow';

const a: Result<number, number> = err(1);
const b: Result<number, number> = a.orElse(() => ok('A'));
console.log(b);
```
```
$ npx tsc
$ node main.js
Ok { value: 'A' }
```
The ok type of `b` is `string`, but TypeScript thinks it is `number`.

`ResultAsync`  is fine. It rejects ok type changes.
```typescript
import { ResultAsync, okAsync, errAsync } from 'neverthrow';

const a: ResultAsync<number, number> = errAsync(1);
const b: ResultAsync<number, number> = a.orElse(() => okAsync('A'));
b.then((r) => console.log(r));
```
```
$ npx tsc
main.ts:4:7 - error TS2322: Type 'ResultAsync<number, unknown>' is not assignable to type 'ResultAsync<number, number>'.
  Type 'unknown' is not assignable to type 'number'.

4 const b: ResultAsync<number, number> = a.orElse(() => okAsync('A'));
        ~

main.ts:4:55 - error TS2769: No overload matches this call.
  Overload 1 of 3, '(f: (e: number) => Result<number, unknown>): ResultAsync<number, unknown>', gave the following error.
    Type 'ResultAsync<string, never>' is not assignable to type 'Result<number, unknown>'.
      Type 'ResultAsync<string, never>' is missing the following properties from type 'Err<number, unknown>': error, isOk, isErr, asyncAndThen, and 3 more.
  Overload 2 of 3, '(f: (e: number) => ResultAsync<number, unknown>): ResultAsync<number, unknown>', gave the following error.
    Type 'ResultAsync<string, never>' is not assignable to type 'ResultAsync<number, unknown>'.
      Type 'string' is not assignable to type 'number'.
  Overload 3 of 3, '(f: (e: number) => Result<number, never> | ResultAsync<number, never>): ResultAsync<number, never>', gave the following error.
    Type 'ResultAsync<string, never>' is not assignable to type 'Result<number, never> | ResultAsync<number, never>'.
      Type 'ResultAsync<string, never>' is not assignable to type 'ResultAsync<number, never>'.
        Type 'string' is not assignable to type 'number'.

4 const b: ResultAsync<number, number> = a.orElse(() => okAsync('A'));
                                                        ~~~~~~~~~~~~

  node_modules/neverthrow/dist/index.d.ts:19:45
    19     orElse<R extends Result<T, unknown>>(f: (e: E) => R): ResultAsync<T, InferErrTypes<R>>;
                                                   ~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  node_modules/neverthrow/dist/index.d.ts:20:50
    20     orElse<R extends ResultAsync<T, unknown>>(f: (e: E) => R): ResultAsync<T, InferAsyncErrTypes<R>>;
                                                        ~~~~~~~~~~~
    The expected type comes from the return type of this signature.
  node_modules/neverthrow/dist/index.d.ts:21:18
    21     orElse<A>(f: (e: E) => Result<T, A> | ResultAsync<T, A>): ResultAsync<T, A>;
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.


Found 2 errors in the same file, starting at: main.ts:4
```

### PR DESCRIPTION
**Pull request by braxtonhall**
- resolves #411 
- resolves #437 

Unfortunately this would be a breaking change, as anyone who explicitly annotated the types like `orElse<A>(foo)` will need to update their code to `orElse<U, A>(foo)`

### CODE REVIEW

**Comment by supermacro** [comment]
https://github.com/supermacro/neverthrow/issues/496

**Comment by myftija** [comment]
@supermacro Any updates on this? Would be really great to have this behavior for `orElse` :)

**Comment by jdisho** [comment]
👍

**Comment by braxtonhall** [comment]
It is possible to make this PR _not_ a breaking change
```diff
- orElse<U, A>(f: (e: E) => Result<U, A> | ResultAsync<U, A>): ResultAsync<U | T, A>
+ orElse<A, U = T>(f: (e: E) => Result<U, A> | ResultAsync<U, A>): ResultAsync<U | T, A>
```
That way anyone who has already annotated the type arguments `orElse<Foo>` will have the same behaviour as before.

The downside is of course that this is really awkward to use, especially as it swaps the order or the ok value type and the err value type. I would guess that would be super error prone and surprising to users.

**Comment by supermacro** [comment]
I think it's OK for this to be implemented as a breaking change. 

### Actions:

- please include a changeset file
- resolve merge conflicts

**Comment by braxtonhall** [comment]
> I think it's OK for this to be implemented as a breaking change.
> 
> ### Actions:
> * please include a changeset file
> * resolve merge conflicts
> * update docs [here](https://github.com/supermacro/neverthrow?tab=readme-ov-file#resultorelse-method) and [here](https://github.com/supermacro/neverthrow?tab=readme-ov-file#resultasyncorelse-method)

Done! (i think)

**Review by m-shaka — APPROVED** [review]
LGTM!

@supermacro if the PR is merged, changesets will create the release PR of v8.0.0.
I'll leave the timing of the merge up to you.

**Pull request merged**
